### ISSUE TITLE
Getting Invalid partition while running Main.scala

### ISSUE THREAD

**Issue by jadireddi** [omearac/reactive-kafka-microservice-template#4]
Hi,

Followed steps described in Link : https://github.com/omearac/reactive-kafka-microservice-template/blob/master/README.md to make kafka Up.

Getting below issue while running Main.scala
```
ERROR] a.a.RepointableActorRef: Error in stage [akka.kafka.internal.ProducerStage@9de0abb]: Invalid partition given with record: 4 is not in the range [0...0]. 
java.lang.IllegalArgumentException: Invalid partition given with record: 4 is not in the range [0...0].
	at org.apache.kafka.clients.producer.KafkaProducer.partition(KafkaProducer.java:717) ~[kafka-clients-0.10.0.1.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:459) ~[kafka-clients-0.10.0.1.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:430) ~[kafka-clients-0.10.0.1.jar:na]
	at akka.kafka.internal.ProducerStage$$anon$1$$anon$3.onPush(ProducerStage.scala:67) ~[akka-stream-kafka_2.11-0.13.jar:0.13]
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747) ~[akka-stream_2.11-2.4.16.jar:na]
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:710) ~[akka-stream_2.11-2.4.16.jar:na]
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:616) ~[akka-stream_2.11-2.4.16.jar:na]
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471) ~[akka-stream_2.11-2.4.16.jar:na]
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:410) ~[akka-stream_2.11-2.4.16.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603) ~[akka-stream_2.11-2.4.16.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618) ~[akka-stream_2.11-2.4.16.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:496) ~[akka-actor_2.11-2.4.16.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529) ~[akka-stream_2.11-2.4.16.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) ~[akka-actor_2.11-2.4.16.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) ~[akka-actor_2.11-2.4.16.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) ~[akka-actor_2.11-2.4.16.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) ~[akka-actor_2.11-2.4.16.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
```

**Comment by jadireddi** [comment]
I upgraded  to latest reactive-kafka i.e  0.16 and executed  Main.scala. Got below error,
```
a.a.RepointableActorRef: Error in stage [akka.kafka.internal.ProducerStage@aa6d328]: Invalid partition given with record: 4 is not in the range [0...1]. 
java.lang.IllegalArgumentException: Invalid partition given with record: 4 is not in the range [0...1].
	at org.apache.kafka.clients.producer.KafkaProducer.partition(KafkaProducer.java:717) ~[kafka-clients-0.10.0.1.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:459) ~[kafka-clients-0.10.0.1.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:430) ~[kafka-clients-0.10.0.1.jar:na]
	at akka.kafka.internal.ProducerStage$$anon$1$$anon$3.onPush(ProducerStage.scala:67) ~[akka-stream-kafka_2.11-0.13.jar:0.13]
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747) ~[akka-stream_2.11-2.4.16.jar:na]
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:710) ~[akka-stream_2.11-2.4.16.jar:na]
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:616) ~[akka-stream_2.11-2.4.16.jar:na]
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471) ~[akka-stream_2.11-2.4.16.jar:na]
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:410) ~[akka-stream_2.11-2.4.16.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603) ~[akka-stream_2.11-2.4.16.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618) ~[akka-stream_2.11-2.4.16.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:496) ~[akka-actor_2.11-2.4.16.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529) ~[akka-stream_2.11-2.4.16.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) ~[akka-actor_2.11-2.4.16.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) ~[akka-actor_2.11-2.4.16.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) ~[akka-actor_2.11-2.4.16.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) ~[akka-actor_2.11-2.4.16.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
```
I modified partition=1 in all areas, and it stared working.

**Comment by omearac** [comment]
Hi there!

Yep the partition numbers in the application.conf file must be equal to the partitions you create in kafka. 

A typical problem that happens all the time in kafka whenever I forget the partition number during topic creation using kafkas CLI.

Did you originally create the topics with partition number equal to 5? The stack trace shows that the code is understanding there are 5 partitions in the topic but Kafka itself doesn't have that many.

**Comment by jadireddi** [comment]
ya true @omearac ..  I created partitions as 5 from CLI. Now above issue is not occurring. Thank you for the help. It's not a bug anymore.
